<?php

namespace ChamaicaineBundle\Repository;

/**
 * DateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DateRepository extends \Doctrine\ORM\EntityRepository
{
    public function dateByDesc() {
        $now = new \DateTime();
        $dead = $now->modify('-1 month');

        $q = $this->createQueryBuilder('d')
            ->select()
            ->where('d.date > :dead')
            ->orderBy('d.date', 'desc')
            ->setParameter('dead', $dead);

        return $q->getQuery()->getResult();
    }
}
