<?php

namespace ChamaicaineBundle\Repository;

/**
 * DescFrRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DescFrRepository extends \Doctrine\ORM\EntityRepository
{
}
