<?php

namespace ChamaicaineBundle\Repository;

/**
 * DescEnRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DescEnRepository extends \Doctrine\ORM\EntityRepository
{
}
