ChamaicaineBundle\Entity\MailList:
    type: entity
    table: null
    repositoryClass: ChamaicaineBundle\Repository\MailListRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        mail:
            type: string
            length: 255
    lifecycleCallbacks: {  }
