chamaicaine_homepage:
    path:     /
    defaults: { _controller: ChamaicaineBundle:Client:home }

chamaicaine_map:
    path: /map
    defaults: { _controller: ChamaicaineBundle:Client:getMap}

cham_admin:
    resource: "routings/admin.yml"
    prefix: /admin
